stages:
  - version
  - build
  - release

default:
  interruptible: false
  tags: 
    - shell

version-bump:
  stage: version
  tags:
    - docker
  image: gitlab.iveydomek.xyz:5050/components/docker/python:latest
  variables:
    GIT_DEPTH: 0
    GL_TOKEN: $GITLAB_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE !~ /^chore: release/'
      when: on_success
  script:
    - pip install "python-semantic-release>=9,<10"
    - export GL_TOKEN="$GITLAB_TOKEN"
    - git config user.email "gitlab-ci@$CI_SERVER_HOST"
    - git config user.name "GitLab CI"
    - git remote set-url origin "https://oauth2:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull origin "$CI_COMMIT_BRANCH"
    - semantic-release version
    - semantic-release publish

include:
  - project: 'components/docker'
    ref: main
    file: template.gitlab-ci.yml
    inputs:
      image_name: finance-manager
      dockerfile: dockerfile
      ci_registry_image: "${CI_REGISTRY}/scripts/finances"
      rules_build:
        - if: '$CI_PIPELINE_SOURCE == "trigger"'
          when: never
        - if: '$CI_COMMIT_BRANCH == "main"'
          changes:
            - app/**/*
          when: on_success
        - when: manual
          allow_failure: true
      rules_release:
        - if: '$CI_PIPELINE_SOURCE == "trigger"'
          when: never
        - if: '$CI_COMMIT_BRANCH == "main"'
          changes:
            - app/**/*
          when: on_success
        - when: manual
          allow_failure: true
