services:
  db:
    container_name: finance_manager_db
    profiles: [db]
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME:-finance-manager}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      TZ: ${TZ:-UTC}
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-finance-manager}"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    container_name: finance_manager_app
    image: ghcr.io/anfer410/finance-manager:${IMAGE_TAG:-latest}
    env_file: .env
    environment:
      APP_ENV: prod
      DB_HOST: 	${DB_HOST:-db}
      DB_NAME: 	${DB_NAME:-finance-manager}
      DB_PASSWORD: 	${DB_PASSWORD:?DB_PASSWORD is required}
      DB_PORT: 	${DB_PORT:-5432}
      DB_USER: 	${DB_USER:-postgres}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
        required: false
    restart: unless-stopped

volumes:
   data: